name: Main CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
#  build:
#    uses: ./.github/workflows/build.yml
  test_api_33to35:
#    needs: build
    uses: ./.github/workflows/test_api_33to35.yml
  test_api_30to32:
    needs: test_api_33to35
    uses: ./.github/workflows/test_api_30to32.yml