name: Main CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
#  build:
#    uses: ./.github/workflows/build.yml
  testing:
#    needs: build
    uses: ./.github/workflows/testing2.yml